services:
  - type: web
    name: anisub
    runtime: python
    buildCommand: "apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PORT
        value: 10000
